export const LOGIN_SUCCESS = "LOGIN_SUCCESS" ; 
export const LOGIN_FAILED = "LOGIN_FAILED" ; 

export const REGISTER_SUCCESS = "REGISTER_SUCCESS" ; 
export const REGISTER_FAIL = "REGISTER_FAIL" ; 
export const LOGOUT = "LOGOUT" ; 

export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL" ; 
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS" ; 

export const BOOK_POST_FAILED = "BOOK_POST_FAILED" ; 
export const BOOK_POST_SUCCESS = "BOOK_POST_SUCCESS" ; 

export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS" ; 
export const FETCH_BOOKS_FAILED ="FETCH_BOOKS_FAILED" ;

export const USER_PROFILE_PICTURE_UPLOAD_FAILED = "USER_PROFILE_PICTURE_UPLOAD_FAILED" ;
export const USER_PROFILE_PICTURE_UPLOAD_SUCCESS = "USER_PROFILE_PICTURE_UPLOAD_SUCCESS" ; 