
export const BOOK_CREATION_STARTED = "BOOK_CREATION_STARTED";
export const BOOK_CREATION_SUCCESS = "BOOK_CREATION_SUCCESS";
export const BOOK_CREATION_FAIL = "BOOK_CREATION_FAIL";

// details
export const BOOK_DETAILS_STARTED = "BOOK_DETAILS_STARTED";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

//Fetch
export const BOOK_FETCH_STARTED = "BOOK_FETCH_STARTED";
export const BOOK_FETCH_SUCCESS = "BOOK_FETCH_SUCCESS";
export const BOOK_FETCH_FAIL = "BOOK_FETCH_FAIL";

//Update
export const BOOK_UPDATE_STARTED = "BOOK_UPDATE_STARTED";
export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";
export const BOOK_UPDATE_FAIL = "BOOK_UPDATE_FAIL";

//Delete
export const BOOK_DELETE_STARTED = "BOOK_DELETE_STARTED";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";

export const BOOK_IMAGE_UPLOAD_SUCCESS = "BOOK_IMAGE_UPLOAD_SUCCESS" ; 
export const BOOK_IMAGE_UPLOAD_FAILED = "BOOK_IMAGE_UPLOAD_FAILED" ; 
